apply plugin: 'com.android.application'

android {
    namespace 'com.google.mlkit.vision.joonb14'
    compileSdk 34

    defaultConfig {
        applicationId "com.google.mlkit.vision.joonb14"
        minSdkVersion 26
        multiDexEnabled true
        targetSdk 34

        renderscriptTargetApi 18
        renderscriptSupportModeEnabled true

        versionCode 11
        versionName "1.11"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    base {
        archivesName.set("vision-quickstart")
    }
    buildTypes {
        proguard {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard.cfg'
            testProguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguardTest-rules.pro', 'proguard.cfg'
        }
        testBuildType "proguard"
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles 'proguard-rules.pro'
        }
    }

    buildFeatures {
        renderScript true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    androidResources {
        noCompress 'tflite'
    }

    // Do NOT compress tflite model files (need to call out to developers!)
}

repositories {
    // Depending on AndroidX Snapshot Builds to get the latest CameraX libs.
    maven { url 'https://androidx.dev/snapshots/builds/6787662/artifacts/repository/' }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.multidex
    //TF Lite
    implementation libs.androidx.multidex
    implementation libs.firebase.ml.model.interpreter
    implementation libs.firebase.analytics
    implementation libs.tensorflow.lite

    // Face features
    implementation libs.face.detection
    // Or comment the dependency above and uncomment the dependency below to
    // use unbundled model that depends on Google Play Services
    // implementation 'com.google.android.gms:play-services-mlkit-face-detection:16.1.4'
    // -------------------------------------------------------

    implementation libs.gson
    implementation libs.guava

    // For how to setup gradle dependencies in Android X, see:
    // https://developer.android.com/training/testing/set-up-project#gradle-dependencies
    // Core library
    androidTestImplementation libs.androidx.core

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation libs.androidx.runner
    androidTestImplementation libs.androidx.rules

    // Assertions
    androidTestImplementation libs.androidx.junit

    // ViewModel and LiveData
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.viewmodel

    implementation libs.androidx.appcompat
    implementation libs.androidx.annotation
    implementation libs.androidx.constraintlayout

    // CameraX
    implementation libs.androidx.camera.camera2
    implementation libs.androidx.camera.lifecycle
    implementation libs.androidx.camera.view

}

configurations {
    // Resolves dependency conflict caused by some dependencies use
    // com.google.guava:guava and com.google.guava:listenablefuture together.
    all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}
// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
apply plugin: 'org.jetbrains.kotlin.android'